version: '3.8'

services:
  nhs-booking-api:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - NHS_ENVIRONMENT=integration
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debugger
    command: ["npm", "run", "dev"]

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nhs-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@nhs.net
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - nhs-network
    profiles:
      - development
